### ISSUE TITLE
Hide real time games from offline players from the "Join a game" list

### ISSUE THREAD

**Issue by ursi** [alcalyn/hex#12]

**Comment by alcalyn** [comment]
Oh there was an issue for that, this has been done in commit https://github.com/alcalyn/hex/commit/497cf6c9d540e20769a140abef565ba760ffe4d5

Games auto-cancels:
- from "Join a game" list, when host is offline for >30sec
- from "Current games", when no move played, and one of the players is offline for >30sec (if one move played, clock will do its job)
