### ISSUE TITLE
Configurable shading patterns

### ISSUE THREAD

**Issue by Bannerets** [alcalyn/hex#16]
It would be nice to have user-configurable display of the shading patterns on the board. Some of the possible options:

- uniformly colored hexes (now)
- tri-color checkerboard-like pattern (used on http://www.mseymour.ca/hexdb.html). makes it easier to see a chain of bridges
- highlight even rows concentrically (used on https://hexworld.org/board/ and BGA)
- a potential experimental one to highlight all height-5 rows in a grid pattern (not used anywhere right now afaik but was proposed before)

Additionally, an independent option to display "star points", i.e., for example, small dots on all four 4-4 points (used on playok), would be useful. The star points (and the aforementioned patterns) make it easier to play bullet games.

(Personally I like the checkerboard-like pattern the most.)

**Comment by alcalyn** [comment]
What are height-5 rows?
Something like this?
![image](https://github.com/alcalyn/hex/assets/1588144/e6ca91f2-f3ef-43ab-b23a-638c4cd16d40)

**Comment by Bannerets** [comment]
no, this: 
![image](https://github.com/alcalyn/hex/assets/10106819/38df1423-bf9f-4687-8f89-cc427ac586ba)

(although first 3 are probably more useful to have)

**Comment by ursi** [comment]
5th rows were my proposal. The logic behind it was that it lets you easily spot rows 4, 5, and 6, which get a lot of action. rows 3 and below are also important of course, but easy to spot without any guides.

**Comment by Bannerets** [comment]
to be clear, "first 3" means the first 3 shading patterns, not rows. When playing bullet games, I frequently felt that I can't quickly find important points without any shading / star points highlighting, so IMO this feature is especially useful in very fast games.
