### ISSUE TITLE
Change win messages

### ISSUE THREAD

**Issue by ursi** [alcalyn/hex#51]
## proposed changes:
{player} won the game! -> {player} won!
{player} won by time! -> {player} won on time!
{player} won by resignation! -> {player} won!
{player} wins the game! -> {player} wins!
{player} wins by time! -> {player} wins on time!
{player} wins by resignation! -> {player} wins!

**Comment by alcalyn** [comment]
Sounds better, you can submit it in weblate, or change it directly in translation files
