### ISSUE TITLE
SGF: add players ratings

### ISSUE THREAD

**Issue by alcalyn** [alcalyn/hex#61]
When generating a SGF file for a game, add [BR](https://www.red-bean.com/sgf/properties.html#BR) and [WR](https://www.red-bean.com/sgf/properties.html#WR) with players ratings.

Ratings must be player rating at the time the game was played.

**Comment by alcalyn** [comment]
Not as easy as it looks: The info is available in rated games, but not for unrated games, so we need to query database to get players rating at this time.

This is acceptable for single game, but not for bulk export, so we also need to add a column in database with current player rating (probably in `HostedGameToPlayer` table).

**Comment by Bannerets** [comment]
Perhaps if the game is unrated, then the players' ratings are irrelevant and could be ignored in the SGF export for this case

**Comment by alcalyn** [comment]
Yes that's true. I guess we can add rating if available, on rated games only, and if really needed, add the column to have rating even on friendly games.

For me, it seems useful to have ratings on friendly games to have an idea, but maybe there won't be real use case

**Comment by alcalyn** [comment]
Done in commit https://github.com/alcalyn/hex/commit/60d20aede983a91f233b56a6d7410c4ab4e02e1c

Only for rated games. Friendly games have no ratings, but can be added in future if there is a need.
