### ISSUE TITLE
Allow choose color on ranked games

### ISSUE THREAD

**Issue by alcalyn** [alcalyn/hex#72]
The "rematch" button gives opposite colors to players, and works.

But if not using it, and creating a rematch game from lobby, it should be possible to choose colors.

Use case: in a tournament, the "rematch" button is not used or wrongly, it should be to recreate a rematch game by hand and choose opposite colors.

**Comment by ursi** [comment]
could you elaborate on the use case? I'm not sure I agree with this. I like the simplicity of ranked always being random.

**Comment by ursi** [comment]
I will also put a message in the chat of the final game reminding the players to use the rematch feature should another game need to be played.

**Comment by alcalyn** [comment]
Ok thanks, I close, in case of unranked, still possible in future to make it ranked and recalculate ratings since this date
