### ISSUE TITLE
Silent Disconnects

### ISSUE THREAD

**Issue by ursi** [alcalyn/hex#73]
Silent disconnects are a real issue. I think we can relatively easily fix this by hooking into the code we already have for refreshing on reconnect, and have it display a popup on disconnect informing the user of the event.

**Comment by alcalyn** [comment]
Yeah very annoying bug... I saw it happened to comonoid while tournament, vs bael, on his video. Let's try this

**Comment by ursi** [comment]
@eilvelia mentioned potentially refreshing the page right as bael made his move. So potentially they actually didn't experience a disconnect but rather a different bug caused by an unfortunate refresh timing. My opponent experienced a disconnect that they blamed on their wifi, but still, there was nothing on the website indicating that it happened.

**Comment by alcalyn** [comment]
I'm also aware of a bug where when you join a game at same time a move is played, you don't receive it. Top item on my bug list since 3 months !

**Comment by eilvelia** [comment]
Yes, the occasional data loss likely cannot be fixed as easily as the original post implies. I would have implemented the networking quite differently. I can perhaps look into fixing these bugs within the next few days

**Comment by ursi** [comment]
I think the data loss issues is a separate issue. alerting the user when they've disconnected seems like a much simpler task.

**Comment by eilvelia** [comment]
I was thinking, we could maybe make an indicator of connection somewhere in the corner, that also shows your ping on click
