### ISSUE TITLE
the hexworld rotation is sometimes incorrect

### ISSUE THREAD

**Issue by eilvelia** [alcalyn/hex#74]
sometimes, when you open a game, the hexwork link opens a board in the https://hexworld.org/board/#14r11c1 (if i remember correctly) rotation. it remains that way until you refresh the page

edit: this is the rotation i have set for the portrait orientation, though the actual screen orientation isn't portrait.

**Comment by ursi** [comment]
I have noticed this as well. have yet to see a consistent trigger for it though.

**Comment by alcalyn** [comment]
Yes I noticed, this is fixed in next release yet. (link was not reactive, computed once at page load, and sometimes before actual orientation defined).
